# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Stephen Hawes
tagline:          ''
description:      'The personal portfolio of Stephen Hawes'
url:              https://www.stephenhawes.com/
baseurl:          ""
url:              ""

author:
  name:           'Stephen Hawes'
  url:            https://github.com/sphawes

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

paginate:         5

collections:
  projects:
    output: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sphawes/portfolio
